app_movie_get_list:
    path: /movies/list/{slug}
    methods: GET
    controller: App\Controller\MovieController::getListAction
    requirements:
        slug: '\w+'

app_user_movie_preference_post:
    path: /movies/preference/
    methods: POST
    controller: App\Controller\UserMovieController::postUserMoviePreferenceAction
