app_movie_get_list:
    path: /movies/list/{slug}
    methods: GET
    controller: App\Controller\MovieController::getListAction
    requirements:
        slug: '.+'

app_user_movie_preference_post:
    path: /movies/preference
    methods: POST
    controller: App\Controller\UserMovieController::postUserMoviePreferenceAction

app_user_movie_preference_delete:
    path: /movies/preference
    methods: DELETE
    controller: App\Controller\UserMovieController::deleteUserMoviePreferenceAction

app_user_movie_recommendations_get:
    path: /movies/user/{userId}/recommendations
    methods: GET
    controller: App\Controller\RecommendationsController::getUserRecommendationsAction
    requirements:
        userId: '\w+'
